//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string Outcome { get; set; }
        public System.DateTime GameDateTime { get; set; }
        public string Venue { get; set; }
        public decimal Fee { get; set; }
        public bool Forfeit { get; set; }
        public int MemberID { get; set; }
        public string Email { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
